title: Exklave Wedding
description: >- # this means to ignore newlines until "baseurl:"
  Exklave im Norden ist ein Teil von dem Wedding und Pankow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.exklave-wedding.de" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  pages:
    output: true
    permalink: /:path/
  events:
    output: true
    permalink: /events/:path

future: true

defaults:
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "default"
